#! /bin/sh

export MONITOR=LVDS-1

bspc monitor $MONITOR -d 1 2 3 4 5

bspc config top_padding          30
bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# focus where mouse is
bspc config focus_follows_pointer true

# dont give desktops to monitors that are off
# bspc config remove_disabled_monitors true
# bspc config remove_unplugged_monitors true

# open on right
bspc config initial_polarity second_child

# window rules
bspc rule -a "Gnomecast" state=floating 
bspc rule -a "feh" state=floating 
bspc rule -a "Matplotlib" state=floating 
bspc rule -a "matplotlib" state=floating 
bspc rule -a "RuneLite Launcher" state=floating 

# startup
sxhkd &
compton -b --config $HOME/.config/compton/compton.conf

$HOME/.config/fehbg
$HOME/.config/polybar/launch.sh &
